### ISSUE TITLE
Code generation requires npx to be globally installed

### ISSUE THREAD

**Issue by tbm206** [dillonkearns/elm-graphql#103]
I don't know if this was a conscious decision but in order to generate graphql schema code, `npx` is required to be globally installed.

#### Steps to produce
1. Install latest version of `@dillonkearns/elm-graphql`.
2. Run `npm run elm-graphql .....`

You'll get:
```
Fetching GraphQL schema...
Generating files...
/bin/sh: npx: command not found
(node:11791) UnhandledPromiseRejectionWarning: Error: Command failed: npx elm-format --elm-version=0.19 --yes src/Api//
/bin/sh: npx: command not found

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:658:13)
    at Object.exports.applyElmFormat (/home/taha/Projects/Private/cpd-awesome/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:19563:21)
    at Array.<anonymous> (/home/taha/Projects/Private/cpd-awesome/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:3493:43)
    at step (/home/taha/Projects/Private/cpd-awesome/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:3414:23)
    at Object.next (/home/taha/Projects/Private/cpd-awesome/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:3395:53)
    at fulfilled (/home/taha/Projects/Private/cpd-awesome/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:3386:58)
(node:11791) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11791) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.37s.
```

### Solution
Install `npx` globally.

However, many developers may not want to install/use `npx`?

**Comment by tbm206** [comment]
Thanks @dillonkearns. I wasn't aware that `npx` is now part of `npm`.

I guess my problem was then caused by my default tendency to use `yarn` instead of `npm`.

Great library BTW :+1:

**Comment by dillonkearns** [comment]
Interesting, I guess you had an old version of npm since you use yarn then?

I think this problem will become less and less frequent over time as people are on newer versions of NPM. I'm open to better solutions if anyone has ideas, but in the meantime this seems like it's in a pretty reasonable state. Thanks for sharing your situation!
