### ISSUE TITLE
GraphQLError on working against schema.graphql generated by absinthe 1.6

### ISSUE THREAD

**Issue by ymtszw** [dillonkearns/elm-graphql#452]
```
/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:39717
  throw (0, _error.syntaxError)(lexer.source, token.start, "Expected \"".concat(value, "\", found ").concat((0, _lexer.getTokenDesc)(token)));
  ^
GraphQLError: Syntax Error: Expected "schema", found String "Represents a schema"
    at syntaxError (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:37451:10)
    at expectKeyword (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:39717:32)
    at parseSchemaDefinition (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:39005:3)
    at parseTypeSystemDefinition (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:38957:16)
    at parseDefinition (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:38404:12)
    at many (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:39773:16)
    at parseDocument (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:38367:18)
    at parse (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:38302:10)
    at Object.buildSchema (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:49061:43)
    at Object.generateOrExitIntrospectionFileFromSchema (/home/ymtszw/workspace/siiibo-app/node_modules/@dillonkearns/elm-graphql/dist/bundle.js:53112:82) {
  locations: [ { line: 1, column: 1 } ]
}
```

The culprit here is description on `schema` directive:
```graphql
# generated by absinthe 1.5
schema {
  query: RootQueryType
  mutation: RootMutationType
}

...
```

```graphql
# generated by absinthe 1.6
"Represents a schema"
schema {
  query: RootQueryType
  mutation: RootMutationType
}

...
```

`"Represents a schema"` is newly inserted line, which causes error.

In graphql spec I assume everything is describe-able, so I believe this is a valid schema file, but no confidence here.
https://spec.graphql.org/June2018/#sec-Descriptions

Which part of the generator needs looking? Or, should this be reported to Absinthe as inconsistency?

Any guidance is appreciated.

**Comment by ymtszw** [comment]
For now I'm dropping first line of the generated code with `| tail -n +2` as a cheap workaround.

**Comment by dillonkearns** [comment]
Hello! This is using the NPM package `graphql` under the hood. It looks like they added support for this syntax in  their [15.0.0 release](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) through this PR https://github.com/graphql/graphql-js/pull/2419.

I think if I merge this pull request from dependabot it should fix it: https://github.com/dillonkearns/elm-graphql/pull/446.

Maybe I can add a little test case to try it out in the end-to-end tests after merging this in. Thanks for reporting the issue!

**Comment by dillonkearns** [comment]
Published! I believe this should be working in the latest NPM release: https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#411---2021-02-03.

Could you try it out and confirm that it's working for you without the workaround now? Thank you!

**Comment by ymtszw** [comment]
Quickness 👍 
And it worked, thanks.
